### ISSUE TITLE
When installing httpd_module 'php' it installs libphp5.so, even though my PHP version is 7

### ISSUE THREAD

**Issue by chris-fa** [chef-cookbooks/httpd#109]
### Cookbook version
0.4

### Chef-client version
Latest from vagrant, `chef_zero`.

### Platform Details
Vbox `bento/centos-6.7`

### Scenario:
Installing Apache PHP module for PHP 7

### Steps to Reproduce:
1. Use yum-remi-chef for php 7
```
include_recipe 'yum-remi-chef::remi-php71'
```

2. Install Apache module
```
httpd_module 'php' do
    instance 'apps'
end
```

### Expected Result:
`cat /etc/httpd-apps/conf.d/php.load` would output `libphp7.so`

### Actual Result:
`cat /etc/httpd-apps/conf.d/php.load` outputs `libphp5.so`

**Comment by iennae** [comment]
Thanks for reporting this issue. The httpd cookbook as written hard codes php5.so in as observed here:
https://github.com/chef-cookbooks/httpd/blob/0722af14e1be3142a8019b21ecf5327c1797e4a5/libraries/httpd_module.rb

**Comment by iennae** [comment]
After copying your test, replicating the outcome that you got, I dug into the httpd_module more. I realized while php5.so is hard coded that the resource definition was assuming that php would just do something that it doesn't know anything about. 

Updated your resource to:

> httpd_module 'php7' do
>     instance 'apps'
>     package_name 'php'
> end

and the outcome is:

> [vagrant@issue-109-centos-67 ~]$ cat /etc/httpd-apps/conf.d/php7.load
> LoadModule php7_module /usr/lib64/httpd/modules/mod_php7.so

In this case, you need to be explicit that you want the php7 module and explicitly name the package with the package_name parameter. The php7.so can be found in is the php package coming from the yum-remi-chef install recipe. (For folks who come by reading this response with regards to debian family packages the resource declaration would be similar but would require modifications based on how php7 got installed and where to find the *.so package.)

This cookbook is one of the cookbooks that we plan to refactor this year so rather than adding technical debt by trying to force a bunch of php7 updates into the code based on the different platforms, I'm going to go ahead and close this. If the above solution doesn't work, please reopen with additional details. 

Thanks!
