### ISSUE TITLE
DocumentRoot?

### ISSUE THREAD

**Issue by lnxchk** [chef-cookbooks/httpd#5]
can has?

**Comment by ameir** [comment]
I think it'd still make sense to offer a resource like `httpd_vhost` that takes in basic parameters (like the server name, server aliases, docroot and log paths) and sets permissions accordingly.  Ideally, a no-frills config like https://github.com/chef-cookbooks/httpd/blob/master/test/fixtures/cookbooks/hello_world_test/templates/default/hello.erb can be shipped and loaded by default with this resource, but be easily overridden for those who need a less-basic vhost config.  Otherwise, users still need to manage paths and permissions outside of the cookbook, which cuts down on adoption a bit, I think.
